name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php8.1
          push: true
          tags: smirik/smirik-php:8.1
      - name: Build and push (DEV)
        uses: docker/build-push-action@v2
        with:
          context: ./php8.1
          file: ./php8.1/Dockerfile.dev
          push: true
          tags: smirik/smirik-php-dev:8.1
      - name: Build and push (ENCORE)
        uses: docker/build-push-action@v2
        with:
          context: ./encore
          file: ./encore/Dockerfile
          push: true
          tags: smirik/smirik-encore
